name = "workers-d1-demo"
main = "./src/index.ts"
compatibility_date = "2023-08-03"
d1_databases = [
    { binding = "Items", database_name = "items", database_id = "00e79be7-7c94-4618-b90e-af02944f65ed" }
]